### ISSUE TITLE
Save not working with ActiveRecord

### ISSUE THREAD

**Issue by SaturnTeam** [yii2tech/embedded#12]
I spent a lot of time while try to find why document is not saving.
So,
`
class SomeClass extends \yii2tech\embedded\mongodb\ActiveRecord {
    public $file; // This is requires to work, but... seriously, why?
    public function embedFile()
    {
        return $this->mapEmbeddedList('file', File::className());
    }
    public function attributes()
    {       
        return ['_id', 'file'];
    }
}
`
So 'file' never save. And I found why. Yii2 save only changed attributes. But, it checks only $this->_attributes array https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L584 . But embeded values puts in different array $this->_embeded.
BaseActiveRecord ignores attributes declared as variables in class. That is why I can't save embeded document. 
So I think there are two solutions:
1) Make Yii2 getDirtyAttributes full check array returned by attributes() and insert values to save there.
2) Set value not only in _embeded. but also in _attributes

**Comment by klimov-paul** [comment]
See https://github.com/yii2tech/embedded/blob/master/mongodb/ActiveRecord.php#L30-L37

**Comment by klimov-paul** [comment]
Resolved by commit 815eac5260ebff09d1d75d98d9b63a9821b93f3c
