### ISSUE TITLE
Populate embedded objects with the query data

### ISSUE THREAD

**Issue by neerajdangol** [yii2tech/embedded#13]
How to populate embedded object properties with the query results? I couldn't find working example in the doc. I've extended my User class from `\yii2tech\embedded\mongodb\ActiveRecord` and everything is same as shown in the example.

```
$user = User::find()->where(['email' => $some_email_address])->one();'
var_dump($user->profile); // Returns Profile object
echo $user->profile-> firstName; //This should return the firstName 
//prints 'Uknown'
```

According to my understanding, above code should return the firstName of the user. But it returns 'Uknown' which is set in the `$profileData` attribute. Am I missing something? Isn't this is how mongodb ActiveRecord supposed to work similar to `\yii\db\ActiveRecord`? Any help is greatly appreciated.

**Comment by klimov-paul** [comment]
Sorry, but do not have time for your education.
All I can suggest for you is trying to reproduce the example from docs step by step.
