### ISSUE TITLE
Support multi level nested subdocuments

### ISSUE THREAD

**Issue by josevavia** [yii2tech/embedded#14]
I am using this extension on a huge project, and I would like to use the extension to manage multiple level nested subdocuments, but after a lot or testing and error, I cant make it work.

Is there any example of how doing this?

The main problem is that examples of this extension show that I need to extend `Model` in the subdocument object, so I can not use the `mapEmbedded` and `mapEmbeddedList` functions to configure the second level, and if I try to extend `ActiveRecord`, I have To implement `attributes ()` function and the mapping starts to fail

**Comment by klimov-paul** [comment]
You should implement `ContainerInterface` and use `ContainerTrait`. There is no matter which class is extended.
