### ISSUE TITLE
Obsolete InvalidParamException in Yii 3

### ISSUE THREAD

**Issue by springimport** [yii2tech/embedded#19]
I think `InvalidParamException` should be replaced by `InvalidArgumentException` in embedded models.

> yii\base\InvalidParamException was renamed to yii\base\InvalidArgumentException.

[Upgrading Instructions for Yii Framework 2.0](https://github.com/yiisoft/yii2/blob/3.0.0-alpha1/framework/UPGRADE.md#upgrade-from-yii-20x).

**Comment by klimov-paul** [comment]
Resolved by commit 11873cd8486295ba27ae109e3de7d5b01c8f68e8
