### ISSUE TITLE
Count property for Validator

### ISSUE THREAD

**Issue by moicirk** [yii2tech/embedded#2]
Hey Paul.
Thank You a lot for this extension, it's very usefull for me in my project.
I have one problem. I use an embedded list in a model, but do not want to use 'createFromNull=false' feature, because it's quite comfort for me to know that I always have iterator even if it`s empty.
Still, I need to validate that amount of embedded objects is more than one, when I try to update a model.

Proposal is to use additional properties for Validator class like 'min', 'max' or just 'count' to validate a size of mapped ArrayObject.

**Comment by klimov-paul** [comment]
This sounds like an `ArrayValidator`. It does not related to the emebedded feature. It is just another validation aspect.
You can create your own implementation for it, or may try to find existing one.

All you need is add it or the virtual attribute, which match embedded model list:

``` php
public function rules()
{
    return [
        ['postModels', 'ArrayValidator', 'min' => 3],
        ['posts', 'yii2tech\embedded\Validator'],
        // ...
    ];
}
```
