### ISSUE TITLE
Can embedded objects be loaded from a nested request?

### ISSUE THREAD

**Issue by yaronius** [yii2tech/embedded#21]
Hi, Paul! First of all, thank you for this very useful library! 
And now to the point. So far it is impossible to load nested models from a nested request (e.g. JSON). Let's take a model from the example:
```
class User extends Model implements ContainerInterface
{
    use ContainerTrait;

    public $profileData = [];

    public function embedProfile()
    {
        return $this->mapEmbedded('profileData', Profile::className());
    }
}
```

When I send the following request:
```
     {
         "profile": {
              "firstName": "John",
              "lastName": "Doe"
          }
     }

```
and populate it with code
```
$user = new User();
$jsonData = JsonHelper::decode(Yii::$app->request->rawBody);
if ($user->load($jsonData) && $user->validate()) {
    // ...
}
```
I get an exception
```
        "name": "Exception",
        "message": "Value should either an object or a null, 'array' given.",
        "code": 0,
        "type": "yii\\base\\InvalidArgumentException",
        "file": "/code/vendor/yii2tech/embedded/src/Mapping.php",
        "line": 79,
```

To deal with it I now override the `setEmbedded()` method like this:
```
public function setEmbedded($name, $value)
{
        $mapping = $this->getEmbeddedMapping($name);
        if (is_array($value) && !$mapping->multiple) {
            // Get embedded model and set its attributes from array
            $attributes = $value;
            $value = $mapping->getValue($this);
            $value->setAttributes($attributes);
        }
        $mapping->setValue($value);
}
```
Now it works just fine.
What do you think of this problem and my solution? Maybe there are some other workarounds I am not aware of?

**Comment by klimov-paul** [comment]
You mixed up source attribute and embedded model.
Your data attribute called `profileData`, while model called `profile`.
The JSON which may populate your models will be:

```
{
         "profileData": {
              "firstName": "John",
              "lastName": "Doe"
          }
     }
```

**Comment by yaronius** [comment]
Thank you for the response. I personally find that using separate data attributes in `profileData` is OK for internal purposes. But when it comes to the terms of convenience, it is really frustrating that I cannot populate the embedded model in a straightforward way without bothering about implementation details. Anyway, thanks for your time.
