### ISSUE TITLE
Embedded attribute is stored in document if corresponding field is present

### ISSUE THREAD

**Issue by comradefuzz** [yii2tech/embedded#22]
### What steps will reproduce the problem?
Define mapped embedded attribute in `fields()`, i.e.:
```
class Page extends \yii2tech\embedded\mongodb\ActiveRecord
{
    use MongoActiveRecordTrait, SetEmbeddedAttributesTrait;

    public function embedDesign()
    {
        return $this->mapEmbedded('designData', PageDesign::class);
    }

    public function fields()
    {
        return [
              'design',
         ];
    }
}
```
Then load post data and save model.

### What is the expected result?
Mongo document having only `designData` section with PageDesign model fields

### What do you get instead?
Mongo document having both  `designData` and `design` sections filled
### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.0.3
| Yii Framework Version | 2.0.32
| PHP version           |  7.1.31
| Operating system      | Debian GNU/Linux 9 (stretch)

### Suggested solution
The problem lies in [this](https://github.com/yii2tech/embedded/blob/master/src/Mapping.php#L184) transformation:
```
 private function extractObjectValues($object)
    {
        $values = ArrayHelper::toArray($object, [], false);
        if ($object instanceof ContainerInterface) {
            $values = array_merge($values, $object->getEmbeddedValues());
        }
        return $values;
    }
```
It seems to be possible to fix this by letting instances of `yii\base\Model` class use `$object->getAttributes()` instead of converting them to array like following:

```
 private function extractObjectValues($object)
    {
        if ($object instanceof yii\base\Model) { 
            $values = $object->getAttributes();
        } else {
            $values = ArrayHelper::toArray($object, [], false);
        }
        if ($object instanceof ContainerInterface) {
            $values = array_merge($values, $object->getEmbeddedValues());
        }
        return $values;
    }
```

**Comment by klimov-paul** [comment]
This is incorrect usage: defined embedded object name should be ever listed at `BaseActiveRecord::fields()` method.

If you with to populate embedded model from request you should either do it explicitly like in [validation example](https://github.com/yii2tech/embedded#validating-embedded-models-) or populate its source attribute and then fetch the embedded object from it.

**Comment by comradefuzz** [comment]
Anyway, the issue is still present wether embedded class is used correctly or not. Mapper must use model attributes as object values.
