### ISSUE TITLE
Error mapping configuration to embeded class

### ISSUE THREAD

**Issue by d52b8** [yii2tech/embedded#24]
When I try use $config to embeded class `MyClass`

``` php
$extraConfig = ['key' => 'value'];
$this->mapEmbeddedList('attribute', MyClass::className(), $config);
```
I get Error

``` php
Setting unknown property: yii2tech\embedded\Mapping::attribute
```

What for this parameter in mapEmbeddedList($source, $target, array `$config = []`) method, if it try use config class `Mapping`, and not embed class `MyClass`?

**Comment by klimov-paul** [comment]
The 3rd argument of `mapEmbeddedList()` is a configuration for the [Mapping](src/Mapping.php) object.
You can find example usage in the unit tests:

https://github.com/yii2tech/embedded/blob/master/tests/ContainerTraitTest.php#L164-L174
https://github.com/yii2tech/embedded/blob/master/tests/data/Container.php#L41-L44

**Comment by d52b8** [comment]
I found solution for my question

``` php
$this->mapEmbeddedList('attribute', array_merge( 
    ['class' => MyClass::className()],
    $extraConfig
));
```

or

``` php
$this->mapEmbeddedList('attribute', [
    MyClass::className(),
    'key' => 'value'
]);
```
