### ISSUE TITLE
How to save (update) nested fields?

### ISSUE THREAD

**Issue by zinzinday** [yii2tech/embedded#4]
I have try to using this validated very well but not save data, i have try debug same time but not work.
Please show me an example about save nested fields.
Thanks advanced

**Comment by klimov-paul** [comment]
I am afraid I don't understand.
You can find enough actual examples at unit tests:
https://github.com/yii2tech/embedded/tree/master/tests

**Comment by kmaurya125** [comment]
@klimov-paul Hi, I have followed doc as well as Testcase https://github.com/yii2tech/embedded/blob/master/tests/ValidatorTest.php.
In model I can see the attribute has the embedded, it is not saving in mongodb. 
`
$model =  new MyServices();
$model->name = 'service_'.uniqid();
$model->messages[] = new MessageModel(['content' => uniqid()]);
$model->messages[] = new MessageModel(['content' => uniqid()]);
$model->save();
`
$model->messages have data before & after save but it's not getting saved in db.
Thanks in advance
