### ISSUE TITLE
Exception on update

### ISSUE THREAD

**Issue by freshua** [yii2tech/embedded#6]
Exception text - "has no declaration ___ for the embedded ___"

Inserting data goes well

**Comment by klimov-paul** [comment]
Please provide the sourc code of your model and full exception stacktrace.

**Comment by freshua** [comment]
> Exception 'yii\base\InvalidParamException' with message ''app\models\User' has no declaration ('embedsocial()') for the embedded 'social'' 
> 
> in /home/andrey/PhpstormProjects/yii2test/vendor/yii2tech/embedded/ContainerTrait.php:168
> 
> Stack trace:
> #0 /home/andrey/PhpstormProjects/yii2test/vendor/yii2tech/embedded/Validator.php(84): app\models\User->getEmbeddedMapping('social')
> #1 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/validators/Validator.php(243): yii2tech\embedded\Validator->validateAttribute(Object(app\models\User), 'social')
> #2 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/base/Model.php(356): yii\validators\Validator->validateAttributes(Object(app\models\User), Array)
> #3 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/db/BaseActiveRecord.php(653): yii\base\Model->validate(NULL)
> #4 /home/andrey/PhpstormProjects/yii2test/controllers/UserController.php(101): yii\db\BaseActiveRecord->update()
> #5 [internal function]: app\controllers\UserController->actionFinishRegister(NULL)
> #6 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
> #7 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
> #8 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('finish-register', Array)
> #9 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/finish-reg...', Array)
> #10 /home/andrey/PhpstormProjects/yii2test/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
> #11 /home/andrey/PhpstormProjects/yii2test/web/index.php(12): yii\base\Application->run()
> #12 {main}

``` php
class User extends ActiveRecord implements \yii\web\IdentityInterface
{

    const STATUS_ENABLED = 100;
    const STATUS_DISABLED = 0;
    const STATUS_EMPTYPROFILE = 90;

    use ContainerTrait;

    public function attributes()
    {
        return ['_id', 'email', 'passwordHash',
            'authKey', 'social', 'token',
            'resetToken', 'profile', 'status'];
    }

    public function embedProfileData()
    {
        return $this->mapEmbeddedList('profile', Profile::className());
    }

    public function embedTokenData()
    {
        return $this->mapEmbedded('token', Token::className());
    }

    public function embedSocialData()
    {
        return $this->mapEmbeddedList('social', Social::className());
    }

    public function rules()
    {
        return [
            [['email', 'status'], 'required'],
            [['passwordHash', 'authKey', 'resetToken'], 'string'],
            [['email'], 'email'],
            [['social', 'profile', 'token'], 'yii2tech\embedded\Validator'],
            [['_id',], 'safe']
        ];
    }

    public static function collectionName()
    {
        return 'users';
    }
```

Do I need a code of embedded models?

**Comment by klimov-paul** [comment]
This is obvious: you have pointed `yii2tech\embedded\Validator` into the wrong property:

``` php
[['social', 'profile', 'token'], 'yii2tech\embedded\Validator'],
```

While it should be:

``` php
[['socialData', 'profileData', 'tokenData'], 'yii2tech\embedded\Validator'],
```

**Comment by v0lume** [comment]
hi paul! i think you should better document this parts. i can't found whats wrong with my code or your extension for about 3 hours, and then i found this issue. thanks for your work!

**Comment by klimov-paul** [comment]
It is documented well enough just here:
https://github.com/yii2tech/embedded#validating-embedded-models-

If you have a better expressions describing the feature - open a PR for the docs update.
